use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.007002
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib examples lib script t xt ) );
__DATA__
irc
יובל
קוג
Yuval
Kogman
nothingmuch
Jesse
Luehrs
doy
Karen
Etheridge
ether
Peter
Rabbitson
ribasushi
Ricardo
Signes
rjbs
Mark
Fowler
mark
Graham
Knop
haarg
Lukas
Mai
mai
Dagfinn
Ilmari
Mannsåker
ilmari
Rudolf
Leermakers
rudolf
anaxagoras
walkeraj
awalker
chromatic
Alex
alex
cm
Andrew
Yates
ayates
David
Lowe
davidl
Glenn
cebjyre
Hans
Dieter
Pearcey
hdp
Jonathan
Yu
JAWNSY
Marc
Mims
marc
Stosberg
Paul
Howarth
paul
lib
Try
Tiny
